server:
  port: 8887

github:
  client:
    id: b4f7f86249a8a17868a7
    secret: cb17a47b537c42f2093797ec676045bd95753e85
    uri: http://localhost:8887/callback

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/community
    username: sa
    password: 123

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: top.perdant.community.model
  mapper-locations: classpath:mapper/*.xml